### ISSUE TITLE
你第一份工作如果是开发相关岗位，请在下面回复相关证据（工牌照片或其他截图之类），不能或者删除此 issues 就说明你是转行的

### ISSUE THREAD

**Issue by tangqx123** [fortune-cook1e/Build-your-own-resume#2]
这是我第一份工作是开发岗位的证明，工牌照片：  
![sj-jpg-869](https://github.com/user-attachments/assets/b05c3674-fd15-4f07-8595-27ec83ea89c7)

你不能提供你的或者删除此 issues 就说明你是转行的，包装简历包装经验进的公司

**Comment by fortune-cook1e** [comment]
首先我根本就不需要跟你这种cs东西证明我从毕业开始都是前端。哎哟 不知道是谁4月份留个言说以后不骚扰了呢 你就是个纯几把神经病 看看下面的截图是谁发的？
![Uploading Snipaste_2024-10-07_17-04-32.png…]()

**Comment by fortune-cook1e** [comment]
不是吧哥们？你找不到证据要我自证？请问 我为什么要跟一个纯畜生傻逼+神经病证明？ 兄弟去个精神病院挂个号吧 天天意淫别人搞你 麻烦再看看某些人3月份留的言 你但凡是个人 我还跟你好声好气说
<img width="795" alt="Snipaste_2024-10-07_17-04-32" src="https://github.com/user-attachments/assets/87db2f6d-8ebd-4394-abd2-8241040228a2">
